# Generated by Django 3.2.8 on 2021-10-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(blank=True, choices=[('manager', 'Менеджер'), ('teamlead', 'Тимлид'), ('developer', 'Разработчик'), ('test_engineer', 'Тест-инженер')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('status', models.CharField(choices=[('to_do', 'To do'), ('In_progress', 'In progress'), ('Code_review', 'Code review'), ('Dev_test', 'Dev test'), ('Testing', 'Testing'), ('Done', 'Done'), ('Wontfix', 'Wontfix')], db_index=True, max_length=20, verbose_name='Статус')),
                ('type', models.CharField(choices=[('BUG', 'bug'), ('TACK', 'tack')], max_length=20, verbose_name='Тип')),
                ('priority', models.CharField(blank=True, choices=[('CRITICAL', 'critical'), ('HIGH', 'high'), ('MEDIUM', 'medium'), ('LOW', 'low')], db_index=True, max_length=20, verbose_name='Приоритет')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_of_change', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='app.user', verbose_name='Создатель')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor', to='app.user', verbose_name='Исполнитель')),
            ],
        ),
    ]
